name: Setup Logtalk
description: Installs the specified Logtalk version
inputs:
  logtalk-version:
    description: Logtalk version to install
    required: true
    default: latest
  logtalk-tool-dependencies:
    description: Install Logtalk tool dependencies
    required: false
    default: true
runs:
  using: 'node16'
  main: 'src/setup-logtalk.js'
branding:
  icon: 'box'
  color: 'blue'
