#!/bin/bash

set -eo pipefail

version=$1
dependencies=$2

cd /tmp

if [ "$version" == "git" ] ; then
	git clone --depth 1 https://github.com/LogtalkDotOrg/logtalk3
	cd logtalk3/scripts
	echo $(git rev-parse HEAD) > /tmp/.logtalk_git_hash
elif [ "$version" == "latest" ] ; then
	wget https://logtalk.org/files/versions.txt
	parsed_version=$(head -n 1 versions.txt)
	wget -nv https://logtalk.org/files/logtalk-$parsed_version.tar.bz2
	sudo tar xjf logtalk-$parsed_version.tar.bz2
	cd logtalk-$parsed_version/scripts
	echo "lgt${parsed_version}stable" > /tmp/.logtalk_git_hash
else 
	wget -nv https://logtalk.org/files/logtalk-$version.tar.bz2
	sudo tar xjf logtalk-$version.tar.bz2
	cd logtalk-$version/scripts
	echo "lgt${version}stable" > /tmp/.logtalk_git_hash
fi
sudo ./install.sh -p /usr/local
logtalk_user_setup

# install coreutils for the timeout option in logtalk_tester
brew install coreutils

if [ "$dependencies" == "true" ] ; then
	# install xsltproc and dot for use with Logtalk tools
	brew install libxslt
	brew install graphviz
	# install basic utilities for thr Logtalk packs tool
	brew install coreutils
	brew install libarchive
	brew install gnupg2
	brew install curl
	brew install wget
	brew install git
	# install Sphinx and dependencies
	sudo python3 -m pip install --upgrade sphinx
	sudo python3 -m pip install --upgrade sphinx_rtd_theme
	# install xunit-viewer to convert xUnit reports to HTML
	sudo npm i -g xunit-viewer
	# install xunit-to-html to convert xUnit reports to HTML
	cd ~
	git clone https://github.com/Zir0-93/xunit-to-html.git
fi
