#!/bin/bash

set -eo pipefail

version=$1
dependencies=$2

cd /tmp

if [ "$version" == "git" ] ; then
	wget https://github.com/LogtalkDotOrg/logtalk3/archive/master.zip
	unzip master.zip
	cd logtalk3-master/scripts
elif [ "$version" == "latest" ] ; then
	wget https://logtalk.org/files/versions.txt
	parsed_version=$(head -n 1 versions.txt)
	wget https://logtalk.org/files/logtalk-$parsed_version.tar.bz2
	sudo tar xjf logtalk-$parsed_version.tar.bz2
	cd logtalk-$parsed_version/scripts
else 
	wget https://logtalk.org/files/logtalk-$version.tar.bz2
	sudo tar xjf logtalk-$version.tar.bz2
	cd logtalk-$version/scripts
fi
sudo ./install.sh -p /usr/local
logtalk_user_setup

if [ "$dependencies" == "true" ] ; then
	# install xsltproc and dot for use with Logtalk tools
	sudo apt-get update -y
	sudo apt-get install -y xsltproc
	sudo apt-get install -y graphviz
	# install basic utilities for thr Logtalk packs tool
	sudo apt-get install -y coreutils
	sudo apt-get install -y libarchive-tools
	sudo apt-get install -y gnupg2
	sudo apt-get install -y curl
	sudo apt-get install -y git
	# install Sphinx and dependencies
	sudo pip3 install --upgrade sphinx
	sudo pip3 install --upgrade sphinx_rtd_theme
	sudo pip3 install --upgrade pygments
	# install xunit-viewer to convert xUnit reports to HTML
	sudo npm i -g xunit-viewer
	# install xunit-to-html to convert xUnit reports to HTML
	cd ~
	git clone https://github.com/Zir0-93/xunit-to-html.git
fi
