#!/bin/bash

set -eo pipefail

version=$1

cd /tmp

if [ "$version" == "git" ] ; then
	wget https://github.com/LogtalkDotOrg/logtalk3/archive/master.zip
	unzip master.zip
	cd logtalk3-master/scripts
elif [ "$version" == "latest" ] ; then
	wget https://logtalk.org/files/versions.txt
	parsed_version=$(head -n 1 versions.txt)
	wget https://logtalk.org/files/logtalk-$parsed_version.tar.bz2
	sudo tar xjvf logtalk-$parsed_version.tar.bz2
	cd logtalk-$parsed_version/scripts
else 
	wget https://logtalk.org/files/logtalk-$version.tar.bz2
	sudo tar xjvf logtalk-$version.tar.bz2
	cd logtalk-$version/scripts
fi
sudo ./install.sh -p /usr/local
logtalk_user_setup

# install xsltproc and dot for use with Logtalk tools
brew install libxslt
brew install graphviz
# install Sphinx and dependencies
sudo pip3 install --upgrade sphinx
sudo pip3 install --upgrade sphinx_rtd_theme
sudo pip3 install --upgrade pygments
